"""esquema base

Revision ID: 0001
Revises:
Create Date: 2026-07-09 15:20:58.962223

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Identificadores de la revisión (usados por Alembic).
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_tasa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('momento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_tasa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_tasa_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_tasa_momento'), ['momento'], unique=False)

    op.create_table('hipervisores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('plataforma', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('ip_gestion', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('marca_modelo', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ubicacion', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ram', sa.String(length=60), server_default='', nullable=False),
    sa.Column('cpu', sa.String(length=120), server_default='', nullable=False),
    sa.Column('almacenamiento', sa.String(length=120), server_default='', nullable=False),
    sa.Column('numero_serie', sa.String(length=120), server_default='', nullable=False),
    sa.Column('garantia_hasta', sa.String(length=40), server_default='', nullable=False),
    sa.Column('proveedor', sa.String(length=120), server_default='', nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('etiquetas', sa.String(length=255), server_default='', nullable=False),
    sa.Column('notas_cifradas', sa.LargeBinary(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('servidores_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=120), nullable=False),
    sa.Column('marca_modelo', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('ip_gestion', sa.String(length=45), nullable=False),
    sa.Column('ram', sa.String(length=60), server_default='', nullable=False),
    sa.Column('cpu', sa.String(length=120), server_default='', nullable=False),
    sa.Column('almacenamiento', sa.String(length=120), server_default='', nullable=False),
    sa.Column('numero_serie', sa.String(length=120), server_default='', nullable=False),
    sa.Column('garantia_hasta', sa.String(length=40), server_default='', nullable=False),
    sa.Column('proveedor', sa.String(length=120), server_default='', nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('etiquetas', sa.String(length=255), server_default='', nullable=False),
    sa.Column('notas_cifradas', sa.LargeBinary(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('totp_secret_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_habilitado', sa.Boolean(), nullable=False),
    sa.Column('ultimo_otp_usado', sa.String(length=8), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('password_cambiada_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rol IN ('admin', 'operador', 'auditor', 'analista')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('codigos_recuperacion_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_hash')
    )
    with op.batch_alter_table('codigos_recuperacion_mfa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codigos_recuperacion_mfa_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('maquinas_virtuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hipervisor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('etiquetas', sa.String(length=255), server_default='', nullable=False),
    sa.Column('notas_cifradas', sa.LargeBinary(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hipervisor_id'], ['hipervisores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maquinas_virtuales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maquinas_virtuales_hipervisor_id'), ['hipervisor_id'], unique=False)

    op.create_table('registros_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('objeto_tipo', sa.String(length=40), nullable=False),
    sa.Column('objeto_id', sa.String(length=40), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('direccion_ip', sa.String(length=45), nullable=False),
    sa.Column('agente_usuario', sa.String(length=255), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_auditoria_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_auditoria_username'), ['username'], unique=False)

    op.create_table('sesiones_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocada_en', sa.DateTime(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=False),
    sa.Column('agente_usuario', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones_web', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_web_token_hash'), ['token_hash'], unique=True)

    op.create_table('tokens_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_api', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_api_token_hash'), ['token_hash'], unique=True)

    op.create_table('concesiones_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servidor_fisico_id', sa.Integer(), nullable=True),
    sa.Column('hipervisor_id', sa.Integer(), nullable=True),
    sa.Column('maquina_virtual_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('concedido_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint("nivel IN ('ver', 'ver_credenciales')", name='ck_concesiones_nivel'),
    sa.CheckConstraint('(CASE WHEN servidor_fisico_id IS NULL THEN 0 ELSE 1 END + CASE WHEN hipervisor_id IS NULL THEN 0 ELSE 1 END + CASE WHEN maquina_virtual_id IS NULL THEN 0 ELSE 1 END) = 1', name='ck_concesiones_un_activo'),
    sa.ForeignKeyConstraint(['concedido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hipervisor_id'], ['hipervisores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maquina_virtual_id'], ['maquinas_virtuales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servidor_fisico_id'], ['servidores_fisicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'servidor_fisico_id', 'hipervisor_id', 'maquina_virtual_id', name='uq_concesion_usuario_activo')
    )
    with op.batch_alter_table('concesiones_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concesiones_acceso_hipervisor_id'), ['hipervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concesiones_acceso_maquina_virtual_id'), ['maquina_virtual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concesiones_acceso_servidor_fisico_id'), ['servidor_fisico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concesiones_acceso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_fisico_id', sa.Integer(), nullable=True),
    sa.Column('hipervisor_id', sa.Integer(), nullable=True),
    sa.Column('maquina_virtual_id', sa.Integer(), nullable=True),
    sa.Column('usuario_acceso', sa.String(length=120), nullable=False),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('servicio', sa.String(length=60), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('password_rotada_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN servidor_fisico_id IS NULL THEN 0 ELSE 1 END + CASE WHEN hipervisor_id IS NULL THEN 0 ELSE 1 END + CASE WHEN maquina_virtual_id IS NULL THEN 0 ELSE 1 END) = 1', name='ck_credenciales_un_activo'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hipervisor_id'], ['hipervisores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maquina_virtual_id'], ['maquinas_virtuales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servidor_fisico_id'], ['servidores_fisicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credenciales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credenciales_hipervisor_id'), ['hipervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credenciales_maquina_virtual_id'), ['maquina_virtual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credenciales_servidor_fisico_id'), ['servidor_fisico_id'], unique=False)

    op.create_table('historial_credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credencial_id', sa.Integer(), nullable=False),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('rotada_en', sa.DateTime(), nullable=False),
    sa.Column('rotada_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credencial_id'], ['credenciales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_credenciales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_credenciales_credencial_id'), ['credencial_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_credenciales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_credenciales_credencial_id'))

    op.drop_table('historial_credenciales')
    with op.batch_alter_table('credenciales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credenciales_servidor_fisico_id'))
        batch_op.drop_index(batch_op.f('ix_credenciales_maquina_virtual_id'))
        batch_op.drop_index(batch_op.f('ix_credenciales_hipervisor_id'))

    op.drop_table('credenciales')
    with op.batch_alter_table('concesiones_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concesiones_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_concesiones_acceso_servidor_fisico_id'))
        batch_op.drop_index(batch_op.f('ix_concesiones_acceso_maquina_virtual_id'))
        batch_op.drop_index(batch_op.f('ix_concesiones_acceso_hipervisor_id'))

    op.drop_table('concesiones_acceso')
    with op.batch_alter_table('tokens_api', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_api_token_hash'))

    op.drop_table('tokens_api')
    with op.batch_alter_table('sesiones_web', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_web_token_hash'))

    op.drop_table('sesiones_web')
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_username'))
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_fecha'))
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_accion'))

    op.drop_table('registros_auditoria')
    with op.batch_alter_table('maquinas_virtuales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maquinas_virtuales_hipervisor_id'))

    op.drop_table('maquinas_virtuales')
    with op.batch_alter_table('codigos_recuperacion_mfa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codigos_recuperacion_mfa_usuario_id'))

    op.drop_table('codigos_recuperacion_mfa')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    op.drop_table('servidores_fisicos')
    op.drop_table('hipervisores')
    with op.batch_alter_table('eventos_tasa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_tasa_momento'))
        batch_op.drop_index(batch_op.f('ix_eventos_tasa_clave'))

    op.drop_table('eventos_tasa')
    # ### end Alembic commands ###
