"""vm specs y vault personal

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-10 03:28:16.368204

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Identificadores de la revisión (usados por Alembic).
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('usuario_acceso', sa.String(length=120), nullable=False),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('categoria', sa.String(length=20), server_default='cuenta', nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('password_rotada_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("categoria IN ('servicio', 'aplicacion', 'cuenta', 'otro')", name='ck_entradas_vault_categoria'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entradas_vault', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entradas_vault_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('maquinas_virtuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ram', sa.String(length=60), server_default='', nullable=False))
        batch_op.add_column(sa.Column('cpu', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('almacenamiento', sa.String(length=120), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquinas_virtuales', schema=None) as batch_op:
        batch_op.drop_column('almacenamiento')
        batch_op.drop_column('cpu')
        batch_op.drop_column('ram')

    with op.batch_alter_table('entradas_vault', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entradas_vault_usuario_id'))

    op.drop_table('entradas_vault')
    # ### end Alembic commands ###
