"""hash auditoria, alcance y caducidad de token

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-10 16:51:04.811927

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Identificadores de la revisión (usados por Alembic).
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_anterior', sa.String(length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('hash_registro', sa.String(length=64), server_default='', nullable=False))
        batch_op.create_index('ix_auditoria_accion_fecha', ['accion', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_auditoria_hash_registro'), ['hash_registro'], unique=False)

    with op.batch_alter_table('tokens_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alcance', sa.String(length=40), server_default='todo', nullable=False))
        batch_op.add_column(sa.Column('expira_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_api', schema=None) as batch_op:
        batch_op.drop_column('expira_en')
        batch_op.drop_column('alcance')

    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_hash_registro'))
        batch_op.drop_index('ix_auditoria_accion_fecha')
        batch_op.drop_column('hash_registro')
        batch_op.drop_column('hash_anterior')

    # ### end Alembic commands ###
